name: delete-branch
on:
  pull_request:
    branches:
      - 'feature/*'
jobs:
  delete-old-branch:
    if: ${{ github.event.pull_request.merged_at != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const ref = `heads/${context.payload.pull_request.head.ref}`;
            const deleteParams = { owner, repo, ref };

            console.log(`Deleting branch: "${ref}"`);
            try {
              console.log("I will delete!")
            } catch(e) {
              console.log("Cannot delete branch; error:", e);
            }